import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ParticleBackground from '../components/particles/ParticleBackground'
import Eventcomp from '../components/Event/Event'
import Navbarcomp from '../components/Navbar/Navbar'

export default function Events() {
  return (
    <>
      <Head>
        <title>Codewar Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/images/logo.png" />
      </Head>
      <ParticleBackground />
      <Eventcomp />
      <Navbarcomp />

    </>
  )
}