import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ParticleBackground from '../components/particles/ParticleBackground'
import Maincomp from '../components/Main/Main'
import Aboutcomp from '../components/About/About'
import Eventcomp from '../components/Event/Event'
import Navbarcomp from '../components/Navbar/Navbar'
import Footercomp from '../components/Footer/Footer'
import PreLoader from '../components/Preloader/Preloader';
import { useEffect, useState } from 'react'

export default function Home() {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setTimeout(() => setIsLoaded(true), 2000);
  }, []);
  return (
    <>
      <Head>
        <title>Codewar Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <PreLoader isLoaded={isLoaded} />
      <ParticleBackground />
      <Navbarcomp />
      <Maincomp />
      <Footercomp />
    </>
  )
}