import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ParticleBackground from '../components/particles/ParticleBackground'
import Maincomp from '../components/Main/Main'
import Aboutcomp from '../components/About/About'
import Eventcomp from '../components/Event/Event'
import Navbarcomp from '../components/Navbar/Navbar'
import SideBarcomp from "../components/Sidebar/Sidebar";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticleBackground />
      <SideBarcomp>
      </SideBarcomp>
      <Maincomp />
      <Aboutcomp />
      <Eventcomp />
    </>
  )
}
